package com.tca.entities;

import org.hibernate.annotations.GenericGenerator;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Student, an entity class
 */
@Entity
@Table(name="student")
public class Student {
	
	/*
	 * Here I have used UUID (Universally Unique identifier)
	 * it is not sequential, it is a 128-bit random number, 
	 * it is generated by hibernate
	 * 
	 * we can use this, when we want non-sequencial Primary Key
	 * or if we have very large user base
	 */
	
	@Id
	@GenericGenerator(name = "custom_pk_gen", strategy = "com.tca.util.CustomIDGenerator")
	@GeneratedValue(generator = "custom_pk_gen")
	@Column(name="id")
	private String uuid;

	 //To store name of the student
	@Column(name="name", nullable = false)
	private String name;
	
	// To store percentage of the student
	@Column(name="per", columnDefinition = "FLOAT CHECK (per >= 0 and per <= 100)")
	private Double per;


	// setters and getters
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPer() {
		return per;
	}

	public void setPer(Double per) {
		this.per = per;
	}

	//toString() method
	@Override
	public String toString() {
		return "Student [uuid=" + uuid + ", name=" + name + ", per=" + per + "]";
	}
		
}
