package com.tca.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;

/**
 * Student, an entity class
 */
@Entity
@Table(name="student")
public class Student {
	
	/* Here, I have used GenerationType.IDENTITY as primary key generation algorithm
	 * 
	 *  here, hibernate does not create any table or sequence, 
	 *  it delegates primary key generation fully to the database column definition. 
	 *  
	 *   Table generated by hibernate : create table student (per FLOAT CHECK (per >= 0 and per <= 100), rno integer generated by default as identity, name varchar(255) not null, primary key (rno))
	 *   here it used rno integer generated by default as identity, means Postgres provides primary key, hibernate just inserts the rows without, specifying the primary key
	 *   
	 *  Here it relies on the database for, primary key generation.
	 *   
	 */
	@GeneratedValue(strategy = GenerationType.SEQUENCE) // AUTO, INDENTITY, SEQUENCE,TABLE  
	@Column(name="rno")
	private Integer rno;

	 //To store name of the student
	@Column(name="name", nullable = false)
	private String name;
	
	// To store percentage of the student
	@Column(name="per", columnDefinition = "FLOAT CHECK (per >= 0 and per <= 100)")
	private Double per;


	// setters and getters
	public Integer getRno() {
		return rno;
	}

	public void setRno(Integer rno) {
		this.rno = rno;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPer() {
		return per;
	}

	public void setPer(Double per) {
		this.per = per;
	}

	//toString() method
	@Override
	public String toString() {
		return "Student [rno=" + rno + ", name=" + name + ", per=" + per + "]";
	}
		
}
